name: check

on:
  schedule:
  - cron: '0 0,4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master 
      - name: Setup python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requests 
      - name: Pull
        run: |
          git config --local user.email "goonhope@gmail.com"
          git config --local user.name "goonhope"
          git pull origin main
      - name: proxies check
        run: python check.py
      - name: Commit
        run: |
          git add -A
          git commit -m "Update Proxies (`date '+%F %H:%M %Z'`)" -a
          git branch -u origin/main
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main 
